// Expense types
export const GET_EXPENSES = 'GET_EXPENSES'
export const ADD_EXPENSE = 'ADD_EXPENSE'
export const DELETE_EXPENSE = 'DELETE_EXPENSE'
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE'
export const EXPENSES_LOADING = 'EXPENSES_LOADING'
// Authentication types
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
// Error types
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
// Modal types
export const OPEN_UPDATE_MODAL = 'OPEN_UPDATE_MODAL'
export const CLOSE_UPDATE_MODAL = 'CLOSE_UPDATE_MODAL'
export const OPEN_EXPENSE_MODAL = 'OPEN_EXPENSE_MODAL'
export const CLOSE_EXPENSE_MODAL = 'CLOSE_EXPENSE_MODAL'
// Display types
export const OPEN_TABLE_DISPLAY = 'OPEN_TABLE_DISPLAY'
export const CLOSE_TABLE_DISPLAY = 'CLOSE_TABLE_DISPLAY'